#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Generate a complete .env file with secure secrets for Metabase Docker Compose."""

from __future__ import annotations

import argparse
import base64
import os
import secrets
import stat
import sys
import tempfile
from pathlib import Path


def gen_base64(n: int) -> str:
    return base64.b64encode(secrets.token_bytes(n)).decode("ascii")


def build_env() -> str:
    return f"""# =============================================================================
# Metabase Production Environment Variables
# =============================================================================
# Generated by generate-secrets.py — re-run to get new secrets.
# =============================================================================

# --- Image Versions ----------------------------------------------------------
METABASE_VERSION=v0.63.x
POSTGRES_VERSION=17-alpine

# --- Metabase Application Database -------------------------------------------
MB_DB_TYPE=postgres
MB_DB_DBNAME=metabase
MB_DB_PORT=5432
MB_DB_USER=metabase
MB_DB_PASS={gen_base64(24)}
MB_DB_HOST=database

# --- Metabase Settings -------------------------------------------------------
MB_SITE_URL=http://localhost:3000
MB_ENCRYPTION_SECRET_KEY={gen_base64(32)}
MB_JETTY_HOST=0.0.0.0
MB_JETTY_MAXTHREADS=100
MB_ASYNC_QUERY_THREAD_POOL_SIZE=10
JAVA_TOOL_OPTIONS=-Xmx2g
MAX_SESSION_AGE=20160
MB_QUERY_CACHING_MAX_TTL=3024000
MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE=15

# --- Optional: Email / SMTP (uncomment to enable) ----------------------------
# MB_EMAIL_SMTP_HOST=smtp.example.com
# MB_EMAIL_SMTP_PORT=587
# MB_EMAIL_SMTP_USER=
# MB_EMAIL_SMTP_PASSWORD=
# MB_EMAIL_SMTP_SECURITY=starttls

# --- Optional: LDAP (uncomment to enable) ------------------------------------
# MB_LDAP_HOST=ldap.example.com
# MB_LDAP_PORT=389
# MB_LDAP_BIND_DN=
# MB_LDAP_PASSWORD=
# MB_LDAP_USER_BASE=ou=users,dc=example,dc=com
"""


def write_secure_env(path: Path, *, force: bool = False) -> None:
    path = path.expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")

    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    temporary_path = Path(temporary_name)

    try:
        os.fchmod(fd, stat.S_IRUSR | stat.S_IWUSR)
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            fd = -1
            file.write(build_env())
            file.flush()
            os.fsync(file.fileno())

        os.replace(temporary_path, path)
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)

        if stat.S_IMODE(path.stat().st_mode) != 0o600:
            raise PermissionError(f"Could not enforce 0600 permissions on {path}")
    finally:
        if fd != -1:
            os.close(fd)
        temporary_path.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a secure .env file")
    parser.add_argument("path", nargs="?", default=None, type=Path)
    parser.add_argument("--force", action="store_true", help="replace an existing file")
    args = parser.parse_args()

    out = args.path if args.path is not None else Path(__file__).parent / ".env"
    write_secure_env(out, force=args.force)
    print(f"Created {out.expanduser().resolve()} with mode 0600")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import traceback

        traceback.print_exc()
        sys.exit(1)
